###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

#    mariadb:
#      image: mariadb:10.4
#      container_name: ghostfrog-mariadb
#
#      volumes:
#        #- /Volumes/segate/ghostfrodg_data/mysql:/var/lib/mysql
#        #-/Volumes/segate/mysql_svr/spider_v1:/var/lib/mysql
#        #- ./data:/var/lib/mysql
#        - db-data:/var/lib/mysql
#      environment:
#        - MYSQL_ROOT_PASSWORD=root
#        - MYSQL_DATABASE=spider_v1
#        - MYSQL_USER=ghostfrog_usr
#        - MYSQL_PASSWORD=root
#      ports:
#        - 3306:3306

    webserver:
      image: nginx:alpine
      container_name: ghostfrog-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - 80:80

    php-fpm:
      build: phpdocker/php-fpm
      container_name: ghostfrog-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
volumes:
  db-data: